name: Destroy AWS Infrastructure

on:
  workflow_dispatch:  # Allows manual execution from GitHub Actions UI



jobs:
  destroy:
    name: Destroy AWS Resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Validate Terraform
        run: |
          cd terraform
          terraform validate

      - name: Plan Terraform Destroy
        run: |
          cd terraform
          terraform plan -destroy

      - name: Destroy Terraform Resources
        run: |
          cd terraform
          terraform destroy -auto-approve
